MSBuild Amogram.Common.DateTime\Amogram.Common.DateTime.csproj /p:Configuration="net35"
MSBuild Amogram.Common.DateTime\Amogram.Common.DateTime.csproj /p:Configuration="net40"
MSBuild Amogram.Common.DateTime\Amogram.Common.DateTime.csproj /p:Configuration="net45"
MSBuild Amogram.Common.DateTime\Amogram.Common.DateTime.csproj /p:Configuration="net451"
MSBuild Amogram.Common.DateTime\Amogram.Common.DateTime.csproj /p:Configuration="net461"
MSBuild Amogram.Common.DateTime\Amogram.Common.DateTime.csproj /p:Configuration="net46"