MSBuild src\Amogram.Common.DateTime\Amogram.Common.DateTime.csproj /p:Configuration="Debug"
MSBuild src\Amogram.Common.DateTime\Amogram.Common.DateTime.csproj /p:Configuration="net35"
MSBuild src\Amogram.Common.DateTime\Amogram.Common.DateTime.csproj /p:Configuration="net40"
MSBuild src\Amogram.Common.DateTime\Amogram.Common.DateTime.csproj /p:Configuration="net45"
MSBuild src\Amogram.Common.DateTime\Amogram.Common.DateTime.csproj /p:Configuration="net451"
MSBuild src\Amogram.Common.DateTime\Amogram.Common.DateTime.csproj /p:Configuration="net461"
MSBuild src\Amogram.Common.DateTime\Amogram.Common.DateTime.csproj /p:Configuration="net46"